# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 202fcca48050345603d7284c4102c90d6d96a24e0576c108ea1a0af4dbb7162271f29b6c9dcbb0b7e1d7ac81bfee250291ea7435e953c1349520c57c69a69a8b

test:
  secret_key_base: 786193d6ff610b1b7c9a4bda513540193d2e8b2c92b9f22832d1da07277613a1bb4922d2eb10fadac4d93abdf8176feda05fc0228a2a0064fa6841a1b1a43dc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
